---
- hosts: localhost
  become: true
  vars:
    file_contents: "{{ lookup('file', '/dev/shm/tnames.txt') }}"  
    users: "{{ lookup('env', 'USERS') }}"
    
  tasks:
  
    - name: Download hostnames file
      shell: wget -O /dev/shm/tnames.txt https://raw.githubusercontent.com/rw-martin/algo-setup/main/tnames.txt
   
    - name: Set files up
      set_fact:
        files: "{{ users.split(',') }}"      

    - name: Grab random Transformers name from file
      set_fact:
        temphost: "{{ file_contents.split('\n') | random | lower }}"

    - name: Set hostname to selected Transformer name
      shell: /usr/bin/hostnamectl set-hostname {{ temphost }}
      
    - name: register host w/ NextDNS
      shell: curl https://link-ip.nextdns.io/b4ba6a/3d270c2ab3df2f91
      
    - name: Update resolv.conf file w/ NextDNS servers
      shell: wget -O /dev/shm/resolv.conf https://raw.githubusercontent.com/rw-martin/algo-setup/main/resolv.conf&cp /dev/shm/resolv.conf /etc/resolv.conf
    
    - name: Modify local hosts file
      shell: echo "127.0.0.1 {{ temphost }}" >> /etc/hosts

    - name: get random number
      shell: shuf -i 38000-58900 -n 1
      register: portnumber
    
    - name: Replace WG port
      lineinfile:
        path: /opt/algo/configs/localhost/wireguard/{{ item }}.conf
        regex: 'Endpoint ='
        line: 'Endpoint = {{ ansible_facts.eth0.ipv4.address }}:{{ portnumber.stdout }}'
      with_items: "{{ files }}"
  
    - name: Replace WG port in configuration file
      lineinfile:
        path: /opt/algo/config.cfg
        regex: 'wireguard_port:*'
        line: 'wireguard_port: {{ portnumber.stdout }}'

    - name: Replace WG port in wg0 configuration file
      lineinfile:
        path: /etc/wireguard/wg0.conf
        regex: 'ListenPort ='
        line: 'ListenPort = {{ portnumber.stdout }}'

    - name: Allow wireguard traffic to any
      shell: ufw allow in on wg0 to any

    - name: clean up old entry
      shell: ufw delete allow 58797

    - name: Restart Wireguard
      shell: wg-quick down wg0 && wg-quick up wg0
    
    - name: Generate new QR codes
      shell: qrencode -o /opt/algo/configs/localhost/wireguard/{{ item }}.png < /opt/algo/configs/localhost/wireguard/{{ item }}.conf
      with_items: "{{ files }}"
         
    - name: Update UFW 
      shell: ufw allow {{ portnumber.stdout }}
      
    - name: Update hosts file 
      lineinfile:
        path: /etc/hosts
        regex: '127.0.0.1'
        line:  '127.0.0.1 {{ temphost }}'
        
    - name: reboot host
      shell: reboot
