---
- hosts: localhost
  become: true
  
  tasks:
    - name: Check for updates
      shell: apt update
      register: output

    - set_fact:
        rw: "{{ output.stdout | regex_search('\\d+ packages' | string)  }}"
       
    - name: check
      command: "{{ item }}"
      loop:
        - apt update -y      
      when: rw != ""
